name: Update Docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Build & Deploy Storybook Docs
        run: |
          npm run storybook:deploy
